config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about', as: 'about'
    get 'customers/mypage' => 'customers#show'
    get '/customers/confirm_withdraw' => 'customers#confirm_withdraw', as: 'confirm_withdraw'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :customers, only:[:edit, :update]
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show]
    resources :genres, only:[:show]
    get '/orders/complete' => 'orders#complete'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only:[:new, :index, :create, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy] do
       collection do
        delete "destroy_all"
      end
    end
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:show, :index, :new, :create, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :edit, :update, :show]
    resources :order_details, only:[:update]
    resources :orders, only:[:show, :update]
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }


  validates :shipping_fee, presence: true
  validates :amount_billed, presence: true
  validates :payment_method, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :status, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
  
  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.status == "confirm_payment"
      @order_details.update_all(production_status: "waiting_manufacture")
    end
    redirect_to admin_order_path(@order)
  end
  
  private
    def order_params
      params.require(:order).permit(:status)
    end
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h4>注文履歴詳細</h4>
      <table class="table table table-borderless">
        <tr>
          <th>購入者</th>
          <td><%= link_to admin_customer_path(@order.customer), class: "text-dark" do %>
                <%= @order.customer.last_name %><%= @order.customer.first_name %>
              <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postal_code %>
              <%= @order.address %><br>
              <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td><%= form_with model: @order, url: admin_order_path(@order) do |f| %>
                <%= f.select :status, Order.statuses_i18n.invert, {} %>
                <%= f.submit "更新", class: "btn btn-success btn-sm ml-4" %>
              <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% total_price = 0 %>
          <% @order_details.each do|order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price.to_s(:delimited) %></td>
              <td><%= order_detail.quantity %></td>
              <td><%= order_detail.subtotal.to_s(:delimited) %>
       　          <% total_price += order_detail.subtotal %>
              </td>
              <td><%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f| %>
                    <%= f.select :production_status, OrderDetail.production_statuses_i18n.invert, {} %>
                    <%= f.submit "更新", class: "btn btn-success btn-sm ml-3" %>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= total_price.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.shipping_fee.to_s(:delimited) %>円
          </td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td class="font-weight-bold"><%= @order.amount_billed.to_s(:delimited) %>円
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>