config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about', as: 'about'
    get 'customers/mypage' => 'customers#show'
    get '/customers/confirm_withdraw' => 'customers#confirm_withdraw', as: 'confirm_withdraw'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :customers, only:[:edit, :update]
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show]
    resources :genres, only:[:show]
    get '/orders/complete' => 'orders#complete'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only:[:new, :index, :create, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy] do
       collection do
        delete "destroy_all"
      end
    end
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:show, :index, :new, :create, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :edit, :update, :show]
    resources :order_details, only:[:update]
    resources :orders, only:[:show, :update]
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
  
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def get_image(width, height)
   unless image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
   image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }


  validates :shipping_fee, presence: true
  validates :amount_billed, presence: true
  validates :payment_method, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :status, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status: { impossible_manufacture: 0,  waiting_manufacture: 1, manufacturing: 2, finish: 3 }

  def subtotal
    item.with_tax_price * quantity
  end

  validates :price, presence: true
  validates :quantity, presence: true
  validates :production_status, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @orders = Order.page(params[:page]).per(10).order(created_at: :desc)
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item= Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品情報を登録しました"
      redirect_to admin_item_path(@item)
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       flash[:notice] = "商品情報を更新しました"
       redirect_to admin_item_path(@item)
    else
      render 'edit'
    end
  end

   private
    def item_params
      params.require(:item).permit(:genre_id, :name, :introduction, :price, :image, :is_active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    case resource
      when Admin
               admin_root_path
      when Customer
               root_path
    end
  end
  
  def after_sign_out_path_for(resource)
    case resource
      when :admin
               new_admin_session_path
      when :customer
               root_path
    end 
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

　　<%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="border-bottom border-dark">
        <nav class="navbar navbar-expand-lg navbar-light">
          <%= link_to root_path, class: 'navbar-nav' do %>
            <%= image_tag 'cake_logo.jpg', size: '70x70' %>
          <% end %>
          <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
             <% if admin_signed_in? %>
                <li class="nav-item mr-3">
                  <%= link_to admin_items_path, class: 'text-decoration-none text-dark' do %>
                      商品一覧
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to admin_customers_path, class: 'text-decoration-none text-dark' do %>
                      会員一覧
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to admin_root_path, class: 'text-decoration-none text-dark' do %>
                      注文履歴一覧
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to admin_genres_path, class: 'text-decoration-none text-dark' do %>
                      ジャンル一覧
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'text-decoration-none text-dark' do %>
                       ログアウト
                  <% end %>
                </li>
             <% elsif customer_signed_in? %>
                <li class="nav-item mr-5">ようこそ、<%= current_customer.last_name %>さん！</li>
                <li class="nav-item mr-3">
                  <%= link_to customers_mypage_path, class: 'text-decoration-none text-dark' do %>
                        マイページ
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to items_path, class: 'text-decoration-none text-dark' do %>
                         商品一覧
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to cart_items_path, class: 'text-decoration-none text-dark' do %>
                         カート
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to destroy_customer_session_path, method: :delete, class: 'text-decoration-none text-dark' do %>
                         ログアウト
                  <% end %>
                </li>
             <% else %>
                <li class="nav-item mr-3">
                  <%= link_to about_path, class: 'text-decoration-none text-dark' do %>
                          About
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to items_path, class: 'text-decoration-none text-dark' do %>
                          商品一覧
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to new_customer_registration_path, class: 'text-decoration-none text-dark' do %>
                          新規登録
                  <% end %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to new_customer_session_path, class: 'text-decoration-none text-dark' do %>
                          ログイン
                  <% end %>
                </li>
             <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <main>
       <% if flash[:notice] %>
 　　  　　　<p id="notice">
        　 　 <%= flash[:notice] %>
          </p>
       <% else flash[:alert] %>
          <p id="alert">
             <%= flash[:alert] %>
          </p>
       <% end %>
       <%= yield %>
    </main>
    <footer class="border-top border-dark pt-5 pb-4 mt-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>